package project.dnet3.appcit;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by shay on 22/03/2015.
 */
public class TimeTableCategories{

    public static ArrayList<String> getTimeTablesList(){
        ArrayList<String> names = new ArrayList<>(timetables.keySet());
        Collections.sort(names);
        names.add(0, "Select");
        return names;
    }

    public static String getTimeTable(String key){
        return timetables.get(key);
    }

    static Map<String, String> timetables = new HashMap<String , String>() {{
//        put("Select", "Select");
        put("AD.STUDY-SEM2", "AD.STUDY-SEM2");
        put("AD.TLU. DEV", "AD.TLU. DEV");
        put("AI.ADCA1 - BACCT_7_Y1", "AI.ADCA1 - BACCT_7_Y1");
        put("AI.ADCA2 - BACCT_7_Y2", "AI.ADCA2 - BACCT_7_Y2");
        put("AI.ADCA3 - BACCT_7_Y3", "AI.ADCA3 - BACCT_7_Y3");
        put("AI.ADCA4 - BACCT_8_Y4", "AI.ADCA4 - BACCT_8_Y4");
        put("AI.AGRI1 - BAGRI_7_Y1", "AI.AGRI1 - BAGRI_7_Y1");
        put("AI.AGRI2 - BAGRI_7_Y2", "AI.AGRI2 - BAGRI_7_Y2");
        put("AI.AGRI3 - BAGRI_7_Y3", "AI.AGRI3 - BAGRI_7_Y3");
        put("AI.AGRI4 - BAGRI_8_Y4", "AI.AGRI4 - BAGRI_8_Y4");
        put("AI.BBSIS1 - BBISY_8_Y1", "AI.BBSIS1 - BBISY_8_Y1");
        put("AI.BBSIS2 - BBISY_8_Y2", "AI.BBSIS2 - BBISY_8_Y2");
        put("AI.BBSIS3 - BBISY_8_Y3", "AI.BBSIS3 - BBISY_8_Y3");
        put("AI.BBSIS4 - BBISY_8_Y4", "AI.BBSIS4 - BBISY_8_Y4");
        put("AI.ENTB1", "AI.ENTB1");
        put("AI.EV DAIRY1", "AI.EV DAIRY1");
        put("AI.EVBBSAC3 - BACCT_7_Y3", "AI.EVBBSAC3 - BACCT_7_Y3");
        put("AI.EVBBSAC4 - BBAC_8_1", "AI.EVBBSAC4 - BBAC_8_1");
        put("AI.HORT1 - BHORT_7_Y1", "AI.HORT1 - BHORT_7_Y1");
        put("AI.HORT2 - BHORT_7_Y2", "AI.HORT2 - BHORT_7_Y2");
        put("AI.HORT3 - BHORT_7_Y3", "AI.HORT3 - BHORT_7_Y3");
        put("AI.HORT4 - BHORT_8_Y4", "AI.HORT4 - BHORT_8_Y4");
        put("AI.MBSACC", "AI.MBSACC");
        put("AI.MBSINFO", "AI.MBSINFO");
        put("AR.ARCH1 - CARCH_8_Y1", "AR.ARCH1 - CARCH_8_Y1");
        put("AR.ARCH2 - CARCH_8_Y2", "AR.ARCH2 - CARCH_8_Y2");
        put("AR.ARCH3 - CARCH_8_Y3", "AR.ARCH3 - CARCH_8_Y3");
        put("AR.ARCH4 - CARCH_8_Y4", "AR.ARCH4 - CARCH_8_Y4");
        put("AR.ARCH5 - CARCH_9_Y1", "AR.ARCH5 - CARCH_9_Y1");
        put("AR.ARCH6", "AR.ARCH6");
        put("AR.AT1 - TARCH_7_Y1", "AR.AT1 - TARCH_7_Y1");
        put("AR.AT2 - TARCH_7_Y2", "AR.AT2 - TARCH_7_Y2");
        put("AR.AT3 - TARCH_7_Y3", "AR.AT3 - TARCH_7_Y3");
        put("AR.AT4 - TARCH_8_Y4", "AR.AT4 - TARCH_8_Y4");
        put("AR.AT5 - CARCT_9_Y1", "AR.AT5 - CARCT_9_Y1");
        put("AR.AT5R", "AR.AT5R");
        put("AR.IA1 - DIARC_7_Y1", "AR.IA1 - DIARC_7_Y1");
        put("AR.IA2 - DIARC_7_Y2", "AR.IA2 - DIARC_7_Y2");
        put("AR.IA3 - DIARC_7_Y3", "AR.IA3 - DIARC_7_Y3");
        put("AR.IA4 - DIARC_8_Y4", "AR.IA4 - DIARC_8_Y4");
        put("AR.IA5 - DINAR_9_Y1", "AR.IA5 - DINAR_9_Y1");
        put("AS.CD1 - HCOED_7_Y1", "AS.CD1 - HCOED_7_Y1");
        put("AS.CD2 - HCOED_7_Y2", "AS.CD2 - HCOED_7_Y2");
        put("AS.CD3 - HCOED_7_Y3", "AS.CD3 - HCOED_7_Y3");
        put("AS.CD4 - HCOED_8_Y4", "AS.CD4 - HCOED_8_Y4");
        put("AS.CED5", "AS.CED5");
        put("AS.EVCOUNS1 - HCOUI_6_Y1", "AS.EVCOUNS1 - HCOUI_6_Y1");
        put("AS.EVCOUNS2 - HCOUN_6_Y2", "AS.EVCOUNS2 - HCOUN_6_Y2");
        put("AS.EVCOUNS3 - HCOUN_8_Y3", "AS.EVCOUNS3 - HCOUN_8_Y3");
        put("AS.EVCOUNS4 - HCOUN_8_Y4", "AS.EVCOUNS4 - HCOUN_8_Y4");
        put("AS.MAPLT", "AS.MAPLT");
        put("AS.PIM", "AS.PIM");
        put("AS.SC1 - HSOCC_7_Y1", "AS.SC1 - HSOCC_7_Y1");
        put("AS.SC2 - HSOCC_7_Y2", "AS.SC2 - HSOCC_7_Y2");
        put("AS.SC3 - HSOCC_7_Y3", "AS.SC3 - HSOCC_7_Y3");
        put("AS.SC4 - HSOCC_8_Y4", "AS.SC4 - HSOCC_8_Y4");
        put("AS.SS5", "AS.SS5");
        put("BI.BMS1 - SBISC_8_Y1", "BI.BMS1 - SBISC_8_Y1");
        put("BI.BMS2 - SBISC_8_Y2", "BI.BMS2 - SBISC_8_Y2");
        put("BI.BMS3 - SBISC_8_Y3", "BI.BMS3 - SBISC_8_Y3");
        put("BI.BMS4 - SBISC_8_Y4", "BI.BMS4 - SBISC_8_Y4");
        put("BI.BMSDCP - SCPBS_8_Y1", "BI.BMSDCP - SCPBS_8_Y1");
        put("BI.BRBI5", "BI.BRBI5");
        put("BI.EVS4B", "BI.EVS4B");
        put("BI.HS1 - SHERB_8_Y1", "BI.HS1 - SHERB_8_Y1");
        put("BI.HS2 - SHERB_8_Y2", "BI.HS2 - SHERB_8_Y2");
        put("BI.HS3 - SHERB_8_Y3", "BI.HS3 - SHERB_8_Y3");
        put("BI.HS4 - SHERB_8_Y4", "BI.HS4 - SHERB_8_Y4");
        put("BI.MLS - SCPBS_8", "BI.MLS - SCPBS_8");
        put("BI.NHS1 - SHNSC_8_Y1", "BI.NHS1 - SHNSC_8_Y1");
        put("BI.NHS2 - SHNSC_8_Y2", "BI.NHS2 - SHNSC_8_Y2");
        put("BI.NHS3 - SHNSC_8_Y3", "BI.NHS3 - SHNSC_8_Y3");
        put("BI.NHS4 - SHNSC_8_Y4", "BI.NHS4 - SHNSC_8_Y4");
        put("BI.PB1 - SPHBI_8_Y1", "BI.PB1 - SPHBI_8_Y1");
        put("BI.PB2 - SPHBI_8_Y2", "BI.PB2 - SPHBI_8_Y2");
        put("BI.PB3 - SPHBI_8_Y3", "BI.PB3 - SPHBI_8_Y3");
        put("BI.PB4 - SPHBI_8_Y4", "BI.PB4 - SPHBI_8_Y4");
        put("BI.S1B - SBIBI_7_Y1", "BI.S1B - SBIBI_7_Y1");
        put("BI.S2B - SBIBI_7_Y2", "BI.S2B - SBIBI_7_Y2");
        put("BI.S3BA - SFSTE_7_Y3", "BI.S3BA - SFSTE_7_Y3");
        put("BI.S3BB - SBIBI_7_Y3", "BI.S3BB - SBIBI_7_Y3");
        put("BI.S5B", "BI.S5B");
        put("BI.S6B", "BI.S6B");
        put("CA.CM1 - CCNMG_8_Y1", "CA.CM1 - CCNMG_8_Y1");
        put("CA.CM2 - CCNMG_8_Y2", "CA.CM2 - CCNMG_8_Y2");
        put("CA.CM3 - CCNMG_8_Y3", "CA.CM3 - CCNMG_8_Y3");
        put("CA.CM4 - CCNMG_8_Y4", "CA.CM4 - CCNMG_8_Y4");
        put("CA.CM5 - CCOPM_9_Y1", "CA.CM5 - CCOPM_9_Y1");
        put("CA.CMEQS - CMEQS_8_Y1", "CA.CMEQS - CMEQS_8_Y1");
        put("CA.CS1 - CCONS_7_Y1", "CA.CS1 - CCONS_7_Y1");
        put("CA.CS2 - CCONS_7_Y2", "CA.CS2 - CCONS_7_Y2");
        put("CA.CS3E - CCECO_7_Y3", "CA.CS3E - CCECO_7_Y3");
        put("CA.CS3M - CMNGT_7_Y3", "CA.CS3M - CMNGT_7_Y3");
        put("CA.CS4M - CMNGT_8_Y4", "CA.CS4M - CMNGT_8_Y4");
        put("CA.CS4Q - CQSUR_8_Y4", "CA.CS4Q - CQSUR_8_Y4");
        put("CA.EVCS3E", "CA.EVCS3E");
        put("CA.EVCS3M", "CA.EVCS3M");
        put("CA.EVNCCS1", "CA.EVNCCS1");
        put("CA.EVNCCS2", "CA.EVNCCS2");
        put("CA.EVNCCS3", "CA.EVNCCS3");
        put("CA.QS1 - CQTSU_8_Y1", "CA.QS1 - CQTSU_8_Y1");
        put("CA.QS2 - CQTSU_8_Y2", "CA.QS2 - CQTSU_8_Y2");
        put("CA.QS3 - CQTSU_8_Y3", "CA.QS3 - CQTSU_8_Y3");
        put("CA.QS4 - CQTSU_8_Y4", "CA.QS4 - CQTSU_8_Y4");
        put("CC.A&amp;D1_AATDE_9_1", "CC.A&amp;D1_AATDE_9_1");
        put("CC.A&amp;D2_AATDE_9_2", "CC.A&amp;D2_AATDE_9_2");
        put("CC.CRM1 - ACERD_7_Y1", "CC.CRM1 - ACERD_7_Y1");
        put("CC.CRM2 - ACERD_7_Y2", "CC.CRM2 - ACERD_7_Y2");
        put("CC.CRM3 - ACERD_7_Y3", "CC.CRM3 - ACERD_7_Y3");
        put("CC.DCRM1 - AACER_8_Y1", "CC.DCRM1 - AACER_8_Y1");
        put("CC.DCRM2 - AACER_8_Y2", "CC.DCRM2 - AACER_8_Y2");
        put("CC.DCRM3 - AACER_8_Y3", "CC.DCRM3 - AACER_8_Y3");
        put("CC.DCRM4 - AACER_8_Y4", "CC.DCRM4 - AACER_8_Y4");
        put("CC.DFA1 - AFAFA_8_Y1", "CC.DFA1 - AFAFA_8_Y1");
        put("CC.DFA2 - AFAFA_8_Y2", "CC.DFA2 - AFAFA_8_Y2");
        put("CC.DFA3 - AFAFA_8_Y3", "CC.DFA3 - AFAFA_8_Y3");
        put("CC.DFA4 - AFAFA_8_Y4", "CC.DFA4 - AFAFA_8_Y4");
        put("CC.EVAE1", "CC.EVAE1");
        put("CC.EVAE10/AE15", "CC.EVAE10/AE15");
        put("CC.EVAE11/(AE3)", "CC.EVAE11/(AE3)");
        put("CC.EVAE13", "CC.EVAE13");
        put("CC.EVAE14", "CC.EVAE14");
        put("CC.EVAE2/AE9 #", "CC.EVAE2/AE9 #");
        put("CC.EVAE2a/AE4", "CC.EVAE2a/AE4");
        put("CC.EVAE5", "CC.EVAE5");
        put("CC.EVAE7", "CC.EVAE7");
        put("CC.EVAE8(AE8b)", "CC.EVAE8(AE8b)");
        put("CC.EVAE9b", "CC.EVAE9b");
        put("CC.EVAED1", "CC.EVAED1");
        put("CC.EVAED2\\AED7", "CC.EVAED2\\AED7");
        put("CC.EVAED6", "CC.EVAED6");
        put("CC.EVATEV", "CC.EVATEV");
        put("CC.EVDATE", "CC.EVDATE");
        put("CC.EVPFOLIOPREP", "CC.EVPFOLIOPREP");
        put("CC.EVPGAT", "CC.EVPGAT");
        put("CC.EVPGAT2", "CC.EVPGAT2");
        put("CC.EVPGAT3", "CC.EVPGAT3");
        put("CC.FA1 - AFINA_7_Y1", "CC.FA1 - AFINA_7_Y1");
        put("CC.FA2 - AFINA_7_Y2", "CC.FA2 - AFINA_7_Y2");
        put("CC.FA3 - AFINA_7_Y3", "CC.FA3 - AFINA_7_Y3");
        put("CC.HDIP_AADET_8_1", "CC.HDIP_AADET_8_1");
        put("CC.MAAT1_ATHPY_9_1", "CC.MAAT1_ATHPY_9_1");
        put("CC.MAAT2_ATHPY_9_2", "CC.MAAT2_ATHPY_9_2");
        put("CC.MAFARSR", "CC.MAFARSR");
        put("CC.PDS", "CC.PDS");
        put("CC.TVA1_ATAPE_9_1", "CC.TVA1_ATAPE_9_1");
        put("CC.TVA2_ATAPE_9_2", "CC.TVA2_ATAPE_9_2");
        put("CO.CLD4 - KCLDC_8_Y1", "CO.CLD4 - KCLDC_8_Y1");
        put("CO.CLD5 - KCLDC_9_Y1", "CO.CLD5 - KCLDC_9_Y1");
        put("CO.COM1 - KCOMP_7_Y1", "CO.COM1 - KCOMP_7_Y1");
        put("CO.COM2 - KCOMP_7_Y2", "CO.COM2 - KCOMP_7_Y2");
        put("CO.COM3 - KCOMP_7_Y3", "CO.COM3 - KCOMP_7_Y3");
        put("CO.DCOM1 - KSDEV_8_Y1", "CO.DCOM1 - KSDEV_8_Y1");
        put("CO.DCOM2 - KSDEV_8_Y2", "CO.DCOM2 - KSDEV_8_Y2");
        put("CO.DCOM3 - KSDEV_8_Y3", "CO.DCOM3 - KSDEV_8_Y3");
        put("CO.DCOM4 - KSDEV_8_Y4", "CO.DCOM4 - KSDEV_8_Y4");
        put("CO.DCOM5", "CO.DCOM5");
        put("CO.DCOM6", "CO.DCOM6");
        put("CO.DNET1 - KDNET_8_Y1", "CO.DNET1 - KDNET_8_Y1");
        put("CO.DNET2 - KDNET_8_Y2", "CO.DNET2 - KDNET_8_Y2");
        put("CO.DNET3 - KDNET_8_Y3", "CO.DNET3 - KDNET_8_Y3");
        put("CO.DNET4 - KDNET_8_Y4", "CO.DNET4 - KDNET_8_Y4");
        put("CO.EVCISCO", "CO.EVCISCO");
        put("CO.EVCISCO-W", "CO.EVCISCO-W");
        put("CO.EVCOM1", "CO.EVCOM1");
        put("CO.EVCOM2", "CO.EVCOM2");
        put("CO.EVCOM3", "CO.EVCOM3");
        put("CO.EVCOMPTIA - KINET_6_Y1", "CO.EVCOMPTIA - KINET_6_Y1");
        put("CO.EVMScCOMSD", "CO.EVMScCOMSD");
        put("CO.EVPCHW", "CO.EVPCHW");
        put("CO.FREECHOICE", "CO.FREECHOICE");
        put("CO.HCCLD - KCITE_6_Y1", "CO.HCCLD - KCITE_6_Y1");
        put("CO.HDCLD - KCLCO_8_Y1", "CO.HDCLD - KCLCO_8_Y1");
        put("CO.HDMOB - KCMSD_8_Y1", "CO.HDMOB - KCMSD_8_Y1");
        put("CO.HDSDEV - KSWDE_8_Y1", "CO.HDSDEV - KSWDE_8_Y1");
        put("CO.ITM1 - KITMN_8_Y1", "CO.ITM1 - KITMN_8_Y1");
        put("CO.ITM2 - KITMN_8_Y2", "CO.ITM2 - KITMN_8_Y2");
        put("CO.ITM3 - KITMN_8_Y3", "CO.ITM3 - KITMN_8_Y3");
        put("CO.ITM4 - KITMN_8_Y4", "CO.ITM4 - KITMN_8_Y4");
        put("CO.ITS1 - KITSU_6_Y1", "CO.ITS1 - KITSU_6_Y1");
        put("CO.ITS2 - KITSU_6_Y2", "CO.ITS2 - KITSU_6_Y2");
        put("CO.ITS3 - KITSU_7_Y3", "CO.ITS3 - KITSU_7_Y3");
        put("CO.LINUX", "CO.LINUX");
        put("CO.MSCRSCH", "CO.MSCRSCH");
        put("CO.NWS1 - KNSEC_9_1", "CO.NWS1 - KNSEC_9_1");
        put("CO.NWS2 - KNSEC_9_2", "CO.NWS2 - KNSEC_9_2");
        put("CO.SWDEV1 - KSDEV_9_Y1", "CO.SWDEV1 - KSDEV_9_Y1");
        put("CO.VM-WARE", "CO.VM-WARE");
        put("CO.WEB1 - KWEBD_8_Y1", "CO.WEB1 - KWEBD_8_Y1");
        put("CO.WEB2 - KWEBD_8_Y2", "CO.WEB2 - KWEBD_8_Y2");
        put("CO.WEB3 - KWEBD_8_Y3", "CO.WEB3 - KWEBD_8_Y3");
        put("CO.WEB4 - KWEBD_8_Y4", "CO.WEB4 - KWEBD_8_Y4");
        put("CR.BREPH4AT1", "CR.BREPH4AT1");
        put("CR.BREPH4AT2", "CR.BREPH4AT2");
        put("CR.BREPH4AT3", "CR.BREPH4AT3");
        put("CR.BREPH4BT1", "CR.BREPH4BT1");
        put("CR.BREPH4BT2", "CR.BREPH4BT2");
        put("CR.BREPH4BT3", "CR.BREPH4BT3");
        put("CR.BREPH4REFT1", "CR.BREPH4REFT1");
        put("CR.BREPH4REFT2", "CR.BREPH4REFT2");
        put("CR.BREPH4REFT3", "CR.BREPH4REFT3");
        put("CR.BREPH6AT1", "CR.BREPH6AT1");
        put("CR.BREPH6AT2", "CR.BREPH6AT2");
        put("CR.BREPH6AT3", "CR.BREPH6AT3");
        put("CR.BREPH6BT1", "CR.BREPH6BT1");
        put("CR.BREPH6BT2", "CR.BREPH6BT2");
        put("CR.BREPH6BT3", "CR.BREPH6BT3");
        put("CR.BREPH6CT1", "CR.BREPH6CT1");
        put("CR.BREPH6CT2", "CR.BREPH6CT2");
        put("CR.BREPH6CT3", "CR.BREPH6CT3");
        put("CR.BREPH6DT1", "CR.BREPH6DT1");
        put("CR.BREPH6DT2", "CR.BREPH6DT2");
        put("CR.BREPH6DT3", "CR.BREPH6DT3");
        put("CR.BREPH6REFT1", "CR.BREPH6REFT1");
        put("CR.CJPH4REFT1", "CR.CJPH4REFT1");
        put("CR.CJPH4REFT2", "CR.CJPH4REFT2");
        put("CR.CJPH4REFT3", "CR.CJPH4REFT3");
        put("CR.CPFPH4AT1", "CR.CPFPH4AT1");
        put("CR.CPFPH4AT2", "CR.CPFPH4AT2");
        put("CR.CPFPH4AT3", "CR.CPFPH4AT3");
        put("CR.CPFPH4BT2", "CR.CPFPH4BT2");
        put("CR.CPFPH6AT1", "CR.CPFPH6AT1");
        put("CR.CPFPH6AT2", "CR.CPFPH6AT2");
        put("CR.CPFPH6AT3", "CR.CPFPH6AT3");
        put("CR.CPFPH6BT2", "CR.CPFPH6BT2");
        put("CR.CTS1-A", "CR.CTS1-A");
        put("CR.CTS1-B", "CR.CTS1-B");
        put("CR.CTW1 - ECTWB_7_Y1", "CR.CTW1 - ECTWB_7_Y1");
        put("CR.CTW2 - ECTWB_7_Y2", "CR.CTW2 - ECTWB_7_Y2");
        put("CR.CTW3 - ECTWB_7_Y3", "CR.CTW3 - ECTWB_7_Y3");
        put("CR.EVAUTOCERT", "CR.EVAUTOCERT");
        put("CR.EVBREPH4REFT1", "CR.EVBREPH4REFT1");
        put("CR.EVBREPH4REFT2", "CR.EVBREPH4REFT2");
        put("CR.EVBREPH4REFT3", "CR.EVBREPH4REFT3");
        put("CR.EVBREPH6REFT1", "CR.EVBREPH6REFT1");
        put("CR.EVBREPH6REFT2", "CR.EVBREPH6REFT2");
        put("CR.EVBREPH6REFT3", "CR.EVBREPH6REFT3");
        put("CR.EVEMD", "CR.EVEMD");
        put("CR.EVEN287A.T1", "CR.EVEN287A.T1");
        put("CR.EVEN287A.T2", "CR.EVEN287A.T2");
        put("CR.EVEN287A.T3", "CR.EVEN287A.T3");
        put("CR.EVEN287B.T1", "CR.EVEN287B.T1");
        put("CR.EVEN287B.T2", "CR.EVEN287B.T2");
        put("CR.EVEN287B.T3", "CR.EVEN287B.T3");
        put("CR.EVEN287C.T1", "CR.EVEN287C.T1");
        put("CR.EVEN287C.T2", "CR.EVEN287C.T2");
        put("CR.EVEN287C.T3", "CR.EVEN287C.T3");
        put("CR.EVREFINTRO", "CR.EVREFINTRO");
        put("CR.EVWE165", "CR.EVWE165");
        put("CR.FTPH4AT1", "CR.FTPH4AT1");
        put("CR.FTPH4AT2", "CR.FTPH4AT2");
        put("CR.FTPH4AT3", "CR.FTPH4AT3");
        put("CR.FTPH4BT2", "CR.FTPH4BT2");
        put("CR.FTPH4BT3", "CR.FTPH4BT3");
        put("CR.FTPH6AT1", "CR.FTPH6AT1");
        put("CR.FTPH6AT2", "CR.FTPH6AT2");
        put("CR.FTPH6AT3", "CR.FTPH6AT3");
        put("CR.FTPH6BT1", "CR.FTPH6BT1");
        put("CR.LVPH4T1", "CR.LVPH4T1");
        put("CR.LVPH4T2", "CR.LVPH4T2");
        put("CR.LVPH4T3", "CR.LVPH4T3");
        put("CR.LVPH6T1", "CR.LVPH6T1");
        put("CR.LVPH6T2", "CR.LVPH6T2");
        put("CR.LVPH6T3", "CR.LVPH6T3");
        put("CR.MS1 - ECTMS_7_Y1", "CR.MS1 - ECTMS_7_Y1");
        put("CR.MS2 - ECTMS_7_Y2", "CR.MS2 - ECTMS_7_Y2");
        put("CR.MTF1 - EMTEF_6_Y1", "CR.MTF1 - EMTEF_6_Y1");
        put("CR.PDPH4AT1", "CR.PDPH4AT1");
        put("CR.PDPH4AT2", "CR.PDPH4AT2");
        put("CR.PDPH4AT3", "CR.PDPH4AT3");
        put("CR.PDPH6T1", "CR.PDPH6T1");
        put("CR.PDPH6T2", "CR.PDPH6T2");
        put("CR.PDPH6T3", "CR.PDPH6T3");
        put("CR.PLBPH4AT1", "CR.PLBPH4AT1");
        put("CR.PLBPH4AT2", "CR.PLBPH4AT2");
        put("CR.PLBPH4AT3", "CR.PLBPH4AT3");
        put("CR.PLBPH4BT1", "CR.PLBPH4BT1");
        put("CR.PLBPH4BT2", "CR.PLBPH4BT2");
        put("CR.PLBPH4BT3", "CR.PLBPH4BT3");
        put("CR.PLBPH4REFT1", "CR.PLBPH4REFT1");
        put("CR.PLBPH4REFT2", "CR.PLBPH4REFT2");
        put("CR.PLBPH4REFT3", "CR.PLBPH4REFT3");
        put("CR.PLBPH6AT1", "CR.PLBPH6AT1");
        put("CR.PLBPH6AT2", "CR.PLBPH6AT2");
        put("CR.PLBPH6AT3", "CR.PLBPH6AT3");
        put("CR.PLBPH6BT1", "CR.PLBPH6BT1");
        put("CR.PLBPH6BT2", "CR.PLBPH6BT2");
        put("CR.PLBPH6BT3", "CR.PLBPH6BT3");
        put("CR.PLSPH4AT1", "CR.PLSPH4AT1");
        put("CR.PLSPH4AT2", "CR.PLSPH4AT2");
        put("CR.PLSPH4AT3", "CR.PLSPH4AT3");
        put("CR.PLSPH6AT1", "CR.PLSPH6AT1");
        put("CR.PLSPH6AT2", "CR.PLSPH6AT2");
        put("CR.PLSPH6AT3", "CR.PLSPH6AT3");
        put("CR.PP5 SEM1", "CR.PP5 SEM1");
        put("CR.PP5 SEM2", "CR.PP5 SEM2");
        put("CR.REFPH4AT1", "CR.REFPH4AT1");
        put("CR.REFPH4AT2", "CR.REFPH4AT2");
        put("CR.REFPH4AT3", "CR.REFPH4AT3");
        put("CR.REFPH6AT1", "CR.REFPH6AT1");
        put("CR.REFPH6AT2", "CR.REFPH6AT2");
        put("CR.REFPH6AT3", "CR.REFPH6AT3");
        put("CR.WFPH4AT1", "CR.WFPH4AT1");
        put("CR.WFPH4AT2", "CR.WFPH4AT2");
        put("CR.WFPH4AT3", "CR.WFPH4AT3");
        put("CR.WFPH4BT1", "CR.WFPH4BT1");
        put("CR.WFPH4BT2", "CR.WFPH4BT2");
        put("CR.WFPH4BT3", "CR.WFPH4BT3");
        put("CR.WFPH4CT1", "CR.WFPH4CT1");
        put("CR.WFPH4CT2", "CR.WFPH4CT2");
        put("CR.WFPH4CT3", "CR.WFPH4CT3");
        put("CR.WFPH4DT1", "CR.WFPH4DT1");
        put("CR.WFPH4DT2", "CR.WFPH4DT2");
        put("CR.WFPH4DT3", "CR.WFPH4DT3");
        put("CR.WFPH6AT1", "CR.WFPH6AT1");
        put("CR.WFPH6AT2", "CR.WFPH6AT2");
        put("CR.WFPH6AT3", "CR.WFPH6AT3");
        put("CR.WFPH6BT1", "CR.WFPH6BT1");
        put("CR.WFPH6BT2", "CR.WFPH6BT2");
        put("CR.WFPH6BT3", "CR.WFPH6BT3");
        put("CS.CE1 - CCIVL_7_Y1", "CS.CE1 - CCIVL_7_Y1");
        put("CS.CE2 - CCIVL_7_Y2", "CS.CE2 - CCIVL_7_Y2");
        put("CS.CE3 - CCIVL_7_Y3", "CS.CE3 - CCIVL_7_Y3");
        put("CS.CE5", "CS.CE5");
        put("CS.CE6", "CS.CE6");
        put("CS.DSE1 - CSTRU_8_Y1", "CS.DSE1 - CSTRU_8_Y1");
        put("CS.DSE2 - CSTRU_8_Y2", "CS.DSE2 - CSTRU_8_Y2");
        put("CS.DSE3 - CSTRU_8_Y3", "CS.DSE3 - CSTRU_8_Y3");
        put("CS.DSE4 - CSTRU_8_Y4", "CS.DSE4 - CSTRU_8_Y4");
        put("CS.DSE5.CSTRU_9_Y1", "CS.DSE5.CSTRU_9_Y1");
        put("CS.DSE6 - CSTRU_9_Y2", "CS.DSE6 - CSTRU_9_Y2");
        put("CS.EE1 - CENVI_7_Y1", "CS.EE1 - CENVI_7_Y1");
        put("CS.EE2 - CENVI_7_Y2", "CS.EE2 - CENVI_7_Y2");
        put("CS.EE3 - CENVI_7_Y3", "CS.EE3 - CENVI_7_Y3");
        put("CS.ENGCE1 - EOMNI_8_Y1", "CS.ENGCE1 - EOMNI_8_Y1");
        put("CS.ENVENG1 - EENEN_7_Y1", "CS.ENVENG1 - EENEN_7_Y1");
        put("CS.ENVX1 - EENEN_8_Y1", "CS.ENVX1 - EENEN_8_Y1");
        put("CS.EVCE1 - CCIVE_6_Y1", "CS.EVCE1 - CCIVE_6_Y1");
        put("CS.EVCE2 - CCIVE_6_Y2", "CS.EVCE2 - CCIVE_6_Y2");
        put("CS.EVCE3  - CIVE_7_Y3", "CS.EVCE3  - CIVE_7_Y3");
        put("CS.MSCE.CSTRU_9", "CS.MSCE.CSTRU_9");
        put("DE.RPL", "DE.RPL");
        put("EE.BDG-ESB", "EE.BDG-ESB");
        put("EE.DLX5", "EE.DLX5");
        put("EE.DLX6", "EE.DLX6");
        put("EE.ELX1 - EELES_7_Y1", "EE.ELX1 - EELES_7_Y1");
        put("EE.ELX2 - EELES_7_Y2", "EE.ELX2 - EELES_7_Y2");
        put("EE.ELX3 - EELES_7_Y3", "EE.ELX3 - EELES_7_Y3");
        put("EE.ELX4 - EELES_8_Y4", "EE.ELX4 - EELES_8_Y4");
        put("EE.ELX5.EMBED_9_Y1", "EE.ELX5.EMBED_9_Y1");
        put("EE.ELX5.EMBED_9_Y2", "EE.ELX5.EMBED_9_Y2");
        put("EE.EPS1 - EELPS_8_Y1", "EE.EPS1 - EELPS_8_Y1");
        put("EE.EPS2 - EELPS_8_Y2", "EE.EPS2 - EELPS_8_Y2");
        put("EE.EPS3 - EELPS_8_Y3", "EE.EPS3 - EELPS_8_Y3");
        put("EE.EPS4 - EELPS_8_Y4", "EE.EPS4 - EELPS_8_Y4");
        put("EE.ETC1 - EELEC_7_Y1", "EE.ETC1 - EELEC_7_Y1");
        put("EE.ETC2 - EELEC_7_Y2", "EE.ETC2 - EELEC_7_Y2");
        put("EE.ETC3 - EELEC_7_Y3", "EE.ETC3 - EELEC_7_Y3");
        put("EE.ETC5", "EE.ETC5");
        put("EE.EVC&amp;G803", "EE.EVC&amp;G803");
        put("EE.EVC&amp;GB", "EE.EVC&amp;GB");
        put("EE.EVC&amp;GC", "EE.EVC&amp;GC");
        put("EE.EVCADETC", "EE.EVCADETC");
        put("EE.EVDCELEM", "EE.EVDCELEM");
        put("EE.EVELADV6", "EE.EVELADV6");
        put("EE.EVEPSBR", "EE.EVEPSBR");
        put("EE.EVLOGIC1", "EE.EVLOGIC1");
        put("EE.EVLOGIC1T2", "EE.EVLOGIC1T2");
        put("EE.EVLOGIC2", "EE.EVLOGIC2");
        put("MA.ALC", "MA.ALC");
        put("MA.DSA1 - DSA_8_Y1", "MA.DSA1 - DSA_8_Y1");
        put("MA.MAPIM_7_Y1", "MA.MAPIM_7_Y1");
        put("MA.MATH-MSC_9_Y1", "MA.MATH-MSC_9_Y1");
        put("MB.109MU - CR_EMANF_9", "MB.109MU - CR_EMANF_9");
        put("MB.AMT - EAMTE_8_Y4", "MB.AMT - EAMTE_8_Y4");
        put("MB.BIOENG1 - EBIME_7_Y1", "MB.BIOENG1 - EBIME_7_Y1");
        put("MB.BIOENG2 - EBIME_7_Y2", "MB.BIOENG2 - EBIME_7_Y2");
        put("MB.BIOENG3 - EBIME_7_Y3", "MB.BIOENG3 - EBIME_7_Y3");
        put("MB.DBE1 - EBIOM_8_Y1", "MB.DBE1 - EBIOM_8_Y1");
        put("MB.DBE2 - EBIOM_8_Y2", "MB.DBE2 - EBIOM_8_Y2");
        put("MB.DBE3 - EBIOM_8_Y3", "MB.DBE3 - EBIOM_8_Y3");
        put("MB.DBE4 - EBIOM_8_Y4", "MB.DBE4 - EBIOM_8_Y4");
        put("MB.DME1 - EMECH_8_Y1", "MB.DME1 - EMECH_8_Y1");
        put("MB.DME2 - EMECH_8_Y2", "MB.DME2 - EMECH_8_Y2");
        put("MB.DME3 - EMECH_8_Y3", "MB.DME3 - EMECH_8_Y3");
        put("MB.DME4 - EMECH_8_Y4", "MB.DME4 - EMECH_8_Y4");
        put("MB.DME5 - EMENG_9_Y1", "MB.DME5 - EMENG_9_Y1");
        put("MB.DME6", "MB.DME6");
        put("MB.ECQTE_6_Y1", "MB.ECQTE_6_Y1");
        put("MB.EV EVNMAN S1", "MB.EV EVNMAN S1");
        put("MB.EV EVNMAN S2", "MB.EV EVNMAN S2");
        put("MB.EV WAVEN S1", "MB.EV WAVEN S1");
        put("MB.EV WAVEN S2", "MB.EV WAVEN S2");
        put("MB.EV25651", "MB.EV25651");
        put("MB.EV25653", "MB.EV25653");
        put("MB.EV3DIM", "MB.EV3DIM");
        put("MB.EV3DIMS", "MB.EV3DIMS");
        put("MB.EVAMT1 - CR_EAMTN_8", "MB.EVAMT1 - CR_EAMTN_8");
        put("MB.EVASME", "MB.EVASME");
        put("MB.EVASQC - ECQEN_6_Y1", "MB.EVASQC - ECQEN_6_Y1");
        put("MB.EVASQNT", "MB.EVASQNT");
        put("MB.EVBERE", "MB.EVBERE");
        put("MB.EVBERI - EENER_7", "MB.EVBERI - EENER_7");
        put("MB.EVBIOFUELS (ESB)", "MB.EVBIOFUELS (ESB)");
        put("MB.EVCAD", "MB.EVCAD");
        put("MB.EVCADB", "MB.EVCADB");
        put("MB.EVCADCUS", "MB.EVCADCUS");
        put("MB.EVCAE", "MB.EVCAE");
        put("MB.EVCME - ECMEN_6_Y1", "MB.EVCME - ECMEN_6_Y1");
        put("MB.EVCMT - ECMTE_6_Y1", "MB.EVCMT - ECMTE_6_Y1");
        put("MB.EVFLUID", "MB.EVFLUID");
        put("MB.EVINTMATHS", "MB.EVINTMATHS");
        put("MB.EVLEAN2", "MB.EVLEAN2");
        put("MB.EVLMAN", "MB.EVLMAN");
        put("MB.EVMAINTEC1", "MB.EVMAINTEC1");
        put("MB.EVMAINTEC2", "MB.EVMAINTEC2");
        put("MB.EVMECH1 - EMTRO_6_11", "MB.EVMECH1 - EMTRO_6_11");
        put("MB.EVMECH2 - EMTRO_6_12", "MB.EVMECH2 - EMTRO_6_12");
        put("MB.EVMECH3", "MB.EVMECH3");
        put("MB.EVMECH3 - EMTRO_6_13", "MB.EVMECH3 - EMTRO_6_13");
        put("MB.EVMTRON - EPEPN_6_Y1", "MB.EVMTRON - EPEPN_6_Y1");
        put("MB.EVPIPCAD", "MB.EVPIPCAD");
        put("MB.EVPMAN - TPMAN_6_11", "MB.EVPMAN - TPMAN_6_11");
        put("MB.EVPMAN2 - TPMAN_6_12", "MB.EVPMAN2 - TPMAN_6_12");
        put("MB.EVPMANC - TPMCO_6_11", "MB.EVPMANC - TPMCO_6_11");
        put("MB.EVPMANC2 - TPMCO_6_12", "MB.EVPMANC2 - TPMCO_6_12");
        put("MB.EVPPT1 - CR_EPPTN_8", "MB.EVPPT1 - CR_EPPTN_8");
        put("MB.EVPROENG", "MB.EVPROENG");
        put("MB.EVROBO", "MB.EVROBO");
        put("MB.EVSCADA - ESCDA_7_11", "MB.EVSCADA - ESCDA_7_11");
        put("MB.EVSCADAT2 - TSCAD_6_12", "MB.EVSCADAT2 - TSCAD_6_12");
        put("MB.EVSCADAT3 - TSCAD_6_13", "MB.EVSCADAT3 - TSCAD_6_13");
        put("MB.EVSET - ESESY_6", "MB.EVSET - ESESY_6");
        put("MB.EVSETBUILD", "MB.EVSETBUILD");
        put("MB.EVSSGB", "MB.EVSSGB");
        put("MB.EVWIND", "MB.EVWIND");
        put("MB.MENG", "MB.MENG");
        put("MB.METS1 - EMECH_7_Y1", "MB.METS1 - EMECH_7_Y1");
        put("MB.METS2 - EMECH_7_Y2", "MB.METS2 - EMECH_7_Y2");
        put("MB.METS3 - EMECH_7_Y3", "MB.METS3 - EMECH_7_Y3");
        put("MB.METS3M - EMANF_7_Y3", "MB.METS3M - EMANF_7_Y3");
        put("MB.MSCMECH(RSR)", "MB.MSCMECH(RSR)");
        put("MB.PHD", "MB.PHD");
        put("MB.PPT - EPPTE_8_Y4", "MB.PPT - EPPTE_8_Y4");
        put("MB.SOCRATES", "MB.SOCRATES");
        put("MC.ABC1", "MC.ABC1");
        put("MC.ABC2", "MC.ABC2");
        put("MC.EVMEDPRD", "MC.EVMEDPRD");
        put("MC.MAJNM - HJWNM_9_Y1", "MC.MAJNM - HJWNM_9_Y1");
        put("MC.MAMM - RSRCH_9_Y5", "MC.MAMM - RSRCH_9_Y5");
        put("MC.MM1 - HMMED_8_Y1", "MC.MM1 - HMMED_8_Y1");
        put("MC.MM2 - HMMED_8_Y2", "MC.MM2 - HMMED_8_Y2");
        put("MC.MM3 - HMMED_8_Y3", "MC.MM3 - HMMED_8_Y3");
        put("MC.MM4 - HMMED_8_Y4", "MC.MM4 - HMMED_8_Y4");
        put("MC.MM5 - HMDES_9_Y1", "MC.MM5 - HMDES_9_Y1");
        put("MC.PR1 - DDCOM_7_Y1", "MC.PR1 - DDCOM_7_Y1");
        put("MC.PR2 - DDCOM_7_Y2", "MC.PR2 - DDCOM_7_Y2");
        put("MC.PR3 - DDCOM_7_Y3", "MC.PR3 - DDCOM_7_Y3");
        put("MC.PR4 - DVCOM_8_Y4", "MC.PR4 - DVCOM_8_Y4");
        put("MC.PURE8 - BPURE_8_Y1", "MC.PURE8 - BPURE_8_Y1");
        put("MC.PURE9 - BPRNM_9_Y1", "MC.PURE9 - BPRNM_9_Y1");
        put("MG.BS1 - BBUSS_7_Y1", "MG.BS1 - BBUSS_7_Y1");
        put("MG.BS2 - BBUSS_7_Y2", "MG.BS2 - BBUSS_7_Y2");
        put("MG.BS3 - BBUSS_7_Y3", "MG.BS3 - BBUSS_7_Y3");
        put("MG.BS4 - BBUSS_8_Y4", "MG.BS4 - BBUSS_8_Y4");
        put("MG.BS5", "MG.BS5");
        put("MG.BS6", "MG.BS6");
        put("MG.EVBBSMGT1 - BMNGT_7_1+2", "MG.EVBBSMGT1 - BMNGT_7_1+2");
        put("MG.EVBBSMGT2 - BMNGT_7_3", "MG.EVBBSMGT2 - BMNGT_7_3");
        put("MG.EVBBSMGT4 - BBUSN_8_Y1", "MG.EVBBSMGT4 - BBUSN_8_Y1");
        put("MG.EVHCBS1 - BBUSA_6_1", "MG.EVHCBS1 - BBUSA_6_1");
        put("MG.EVHCBS2 - BBUSA_6_2", "MG.EVHCBS2 - BBUSA_6_2");
        put("MG.MBS1 - BBUSE_6_Y1", "MG.MBS1 - BBUSE_6_Y1");
        put("MG.MBS2 - BBUSE_6_Y2", "MG.MBS2 - BBUSE_6_Y2");
        put("MG.XTLGPROV", "MG.XTLGPROV");
        put("MR.BIB1 - BIBLA_8_Y1", "MR.BIB1 - BIBLA_8_Y1");
        put("MR.BS3M - BMKTG_7_Y3", "MR.BS3M - BMKTG_7_Y3");
        put("MR.EVBSSM1", "MR.EVBSSM1");
        put("MR.EVDM1", "MR.EVDM1");
        put("MR.MBSMKT", "MR.MBSMKT");
        put("MR.MRKT1 - BMRKT_8_Y1", "MR.MRKT1 - BMRKT_8_Y1");
        put("MR.MRKT2 - BMRKT_8_Y2", "MR.MRKT2 - BMRKT_8_Y2");
        put("MR.MRKT3 - BMRKT_8_Y3", "MR.MRKT3 - BMRKT_8_Y3");
        put("MR.MRKT4 - BMRKT_8_Y4", "MR.MRKT4 - BMRKT_8_Y4");
        put("MR.MSCMRKT - BMRKP_9_1", "MR.MSCMRKT - BMRKP_9_1");
        put("NS.CL1DK", "NS.CL1DK");
        put("NS.CMM", "NS.CMM");
        put("NS.ETO1 - EMAEL_7_Y1", "NS.ETO1 - EMAEL_7_Y1");
        put("NS.ETO2 - EMAEL_7_Y2", "NS.ETO2 - EMAEL_7_Y2");
        put("NS.ETO3 - EMAEL_7_Y3", "NS.ETO3 - EMAEL_7_Y3");
        put("NS.EVBOATELECT", "NS.EVBOATELECT");
        put("NS.EVBOATENG", "NS.EVBOATENG");
        put("NS.EVBS", "NS.EVBS");
        put("NS.EVBSS", "NS.EVBSS");
        put("NS.EVDKREF", "NS.EVDKREF");
        put("NS.EVEDH", "NS.EVEDH");
        put("NS.EVEFA", "NS.EVEFA");
        put("NS.EVM4 - MM4EN_6_Y1", "NS.EVM4 - MM4EN_6_Y1");
        put("NS.EVMC", "NS.EVMC");
        put("NS.EVMFA", "NS.EVMFA");
        put("NS.EVOCEAN", "NS.EVOCEAN");
        put("NS.EVOOW", "NS.EVOOW");
        put("NS.EVPST", "NS.EVPST");
        put("NS.EVSC", "NS.EVSC");
        put("NS.EVTSC", "NS.EVTSC");
        put("NS.EVYOFF", "NS.EVYOFF");
        put("NS.HC1", "NS.HC1");
        put("NS.HC2", "NS.HC2");
        put("NS.M4 - EMARE_8_Y1", "NS.M4 - EMARE_8_Y1");
        put("NS.MP1 - EMARE_7_Y1", "NS.MP1 - EMARE_7_Y1");
        put("NS.MP2 - EMARE_7_Y2", "NS.MP2 - EMARE_7_Y2");
        put("NS.MP3 - EMARE_7_Y3", "NS.MP3 - EMARE_7_Y3");
        put("NS.NARAS-0", "NS.NARAS-0");
        put("NS.OOW - MOOWE_X_YX", "NS.OOW - MOOWE_X_YX");
        put("NS.SC1 - BSCTM_7_Y1", "NS.SC1 - BSCTM_7_Y1");
        put("NS.SEAMAN3", "NS.SEAMAN3");
        put("NS.TDO1 - SNASC_7_Y1", "NS.TDO1 - SNASC_7_Y1");
        put("NS.TDO2 - SNASC_7_Y2", "NS.TDO2 - SNASC_7_Y2");
        put("NS.TDO3 - SNASC_7_Y3", "NS.TDO3 - SNASC_7_Y3");
        put("NS.TDO4 - SNASC_8_Y1", "NS.TDO4 - SNASC_8_Y1");
        put("OP.ACCAFT", "OP.ACCAFT");
        put("OP.BBADM1 - BBADM_7_Y1", "OP.BBADM1 - BBADM_7_Y1");
        put("OP.BBADM2 - BBADM_7_Y2", "OP.BBADM2 - BBADM_7_Y2");
        put("OP.BBADM3 - BBADM_7_Y3", "OP.BBADM3 - BBADM_7_Y3");
        put("OP.BBADM4 - BBADM_8_Y4", "OP.BBADM4 - BBADM_8_Y4");
        put("OP.EVACCA", "OP.EVACCA");
        put("OP.EVACPA1 - FRM2", "OP.EVACPA1 - FRM2");
        put("OP.EVACPA2 - PROF1", "OP.EVACPA2 - PROF1");
        put("OP.EVACPA3 - PROF2", "OP.EVACPA3 - PROF2");
        put("OP.EVDHRM1 - BHRMN_7_Y1", "OP.EVDHRM1 - BHRMN_7_Y1");
        put("OP.EVDHRM2 - BHRMN_7_Y2", "OP.EVDHRM2 - BHRMN_7_Y2");
        put("OP.EVDHRM3 - BHRMN_7_Y3", "OP.EVDHRM3 - BHRMN_7_Y3");
        put("OP.EVDHRM4 - BHRMN_8_Y4", "OP.EVDHRM4 - BHRMN_8_Y4");
        put("OP.EVIATI-1", "OP.EVIATI-1");
        put("OP.EVIATI-2", "OP.EVIATI-2");
        put("OP.EVMBS-1", "OP.EVMBS-1");
        put("OP.EVPAYROLL", "OP.EVPAYROLL");
        put("OP.EVPHDAE", "OP.EVPHDAE");
        put("OP.EVPHDAE.EVMBS-2", "OP.EVPHDAE.EVMBS-2");
        put("OP.EVRT", "OP.EVRT");
        put("OP.EVRT2", "OP.EVRT2");
        put("OP.MAHRM1 - BHRMN_9_Y1", "OP.MAHRM1 - BHRMN_9_Y1");
        put("PE.AUTO1 - TTMGT_7_Y1", "PE.AUTO1 - TTMGT_7_Y1");
        put("PE.AUTO2 - TTMAT_7_Y2", "PE.AUTO2 - TTMAT_7_Y2");
        put("PE.AUTO3 - TTMAT_7_Y3", "PE.AUTO3 - TTMAT_7_Y3");
        put("PE.AUTO4 - TTMGT_8_Y4", "PE.AUTO4 - TTMGT_8_Y4");
        put("PE.BES1 - EBENS_8_Y1", "PE.BES1 - EBENS_8_Y1");
        put("PE.BES2 - EBENS_8_Y2", "PE.BES2 - EBENS_8_Y2");
        put("PE.BES4 - EBENS_8_Y4", "PE.BES4 - EBENS_8_Y4");
        put("PE.BIS1 - EBSEN_7_Y1", "PE.BIS1 - EBSEN_7_Y1");
        put("PE.BIS2 - EBSEN_7_Y2", "PE.BIS2 - EBSEN_7_Y2");
        put("PE.BIS3 - EBSEN_7_Y3", "PE.BIS3 - EBSEN_7_Y3");
        put("PE.CB1", "PE.CB1");
        put("PE.CBPMO - EBIMO_6_Y1", "PE.CBPMO - EBIMO_6_Y1");
        put("PE.CBPP - EBIPR_7_Y1", "PE.CBPP - EBIPR_7_Y1");
        put("PE.CFDMO - EFDMO_6_Y1", "PE.CFDMO - EFDMO_6_Y1");
        put("PE.DBPMO - EBPMO_7_Y1", "PE.DBPMO - EBPMO_7_Y1");
        put("PE.DCE1 - ECPEN_8_Y1", "PE.DCE1 - ECPEN_8_Y1");
        put("PE.DCE2 - ECPEN_8_Y2", "PE.DCE2 - ECPEN_8_Y2");
        put("PE.DCE3 - ECPEN_8_Y3", "PE.DCE3 - ECPEN_8_Y3");
        put("PE.DCE4 - ECPEN_8_Y4", "PE.DCE4 - ECPEN_8_Y4");
        put("PE.DCE5 - ECHBI_9_Y1", "PE.DCE5 - ECHBI_9_Y1");
        put("PE.DCE6", "PE.DCE6");
        put("PE.EVELEADV", "PE.EVELEADV");
        put("PE.EVELEELEM", "PE.EVELEELEM");
        put("PE.EVELEINT", "PE.EVELEINT");
        put("PE.EVENGADV", "PE.EVENGADV");
        put("PE.EVGMP1", "PE.EVGMP1");
        put("PE.EVGMP2", "PE.EVGMP2");
        put("PE.EVGMP3", "PE.EVGMP3");
        put("PE.EVGMP4", "PE.EVGMP4");
        put("PE.EVGORG", "PE.EVGORG");
        put("PE.EVMIMI", "PE.EVMIMI");
        put("PE.EXPLTECH", "PE.EXPLTECH");
        put("PE.GMP1 - SGMPR_6_Y1", "PE.GMP1 - SGMPR_6_Y1");
        put("PE.GMP2 - SGMPR_6_Y2", "PE.GMP2 - SGMPR_6_Y2");
        put("PE.HCGMP1 - SGMPR_6_Y1", "PE.HCGMP1 - SGMPR_6_Y1");
        put("PE.HCGMP3 - SGMFP_6_Y3", "PE.HCGMP3 - SGMFP_6_Y3");
        put("PE.MSCCENG", "PE.MSCCENG");
        put("PE.PPD1", "PE.PPD1");
        put("PE.SET1 - ESENT_8_Y1", "PE.SET1 - ESENT_8_Y1");
        put("PE.SET2- ESENT_8_Y2", "PE.SET2- ESENT_8_Y2");
        put("PE.SET3 - ESENT_8_Y3", "PE.SET3 - ESENT_8_Y3");
        put("PE.SET4 - ESENT_8_Y4", "PE.SET4 - ESENT_8_Y4");
        put("PS.AIA", "PS.AIA");
        put("PS.BEST1 - SESST_8_Y1", "PS.BEST1 - SESST_8_Y1");
        put("PS.BEST2 - SESST_8_Y2", "PS.BEST2 - SESST_8_Y2");
        put("PS.BEST3 - SESST_8_Y3", "PS.BEST3 - SESST_8_Y3");
        put("PS.BEST4 - SESST_8_Y4", "PS.BEST4 - SESST_8_Y4");
        put("PS.CIMC-A", "PS.CIMC-A");
        put("PS.CIMC-B", "PS.CIMC-B");
        put("PS.CIMC-C", "PS.CIMC-C");
        put("PS.DCH1 - SCHQA_8_Y1", "PS.DCH1 - SCHQA_8_Y1");
        put("PS.DCH2 - SCHQA_8_Y2", "PS.DCH2 - SCHQA_8_Y2");
        put("PS.DCH3 - SCHQA_8_Y3", "PS.DCH3 - SCHQA_8_Y3");
        put("PS.DCH4 - SCHQA_8_Y4", "PS.DCH4 - SCHQA_8_Y4");
        put("PS.DSCI1 - SOMNI_8_Y1", "PS.DSCI1 - SOMNI_8_Y1");
        put("PS.EVDIPQM1", "PS.EVDIPQM1");
        put("PS.EVDIPQM2", "PS.EVDIPQM2");
        put("PS.EVHCQA", "PS.EVHCQA");
        put("PS.EVS3A", "PS.EVS3A");
        put("PS.EVSINDA_6", "PS.EVSINDA_6");
        put("PS.EVSINDA_7", "PS.EVSINDA_7");
        put("PS.EVSINDA_8", "PS.EVSINDA_8");
        put("PS.IE1 - SINEN_8_Y1", "PS.IE1 - SINEN_8_Y1");
        put("PS.IE2 - SINEN_8_Y2", "PS.IE2 - SINEN_8_Y2");
        put("PS.IE3 - SINEN_8_Y3", "PS.IE3 - SINEN_8_Y3");
        put("PS.IE4 - SINEN_8_Y4", "PS.IE4 - SINEN_8_Y4");
        put("PS.IP1 - SPHYS_7_Y1", "PS.IP1 - SPHYS_7_Y1");
        put("PS.IP2 - SPHYS_7_Y2", "PS.IP2 - SPHYS_7_Y2");
        put("PS.IP3 - SPHYS_7_Y3", "PS.IP3 - SPHYS_7_Y3");
        put("PS.IP4 - SPHYS_8_Y4", "PS.IP4 - SPHYS_8_Y4");
        put("PS.IP5", "PS.IP5");
        put("PS.IP6", "PS.IP6");
        put("PS.S1A - SCHEM_7_Y1", "PS.S1A - SCHEM_7_Y1");
        put("PS.S2A - SCHEM_7_Y2", "PS.S2A - SCHEM_7_Y2");
        put("PS.S3A - SCHEM_7_Y3", "PS.S3A - SCHEM_7_Y3");
        put("PS.S5A", "PS.S5A");
        put("PS.S6A", "PS.S6A");
        put("PS.SCI1 - SOMNI_7_Y1", "PS.SCI1 - SOMNI_7_Y1");
        put("SL.EYE1 - HECCE_7_Y1", "SL.EYE1 - HECCE_7_Y1");
        put("SL.EYE2 - HECCE_7_Y2", "SL.EYE2 - HECCE_7_Y2");
        put("SL.EYE3 - HECCE_7_Y3", "SL.EYE3 - HECCE_7_Y3");
        put("SL.EYE4 - HECCE_8_Y4", "SL.EYE4 - HECCE_8_Y4");
        put("SL.EYE5", "SL.EYE5");
        put("SL.MTS3 - HMONT_7_Y1", "SL.MTS3 - HMONT_7_Y1");
        put("SL.MTS4 - HMONT_8_Y4", "SL.MTS4 - HMONT_8_Y4");
        put("SL.PLTH1 - HPLTH_9_Y1", "SL.PLTH1 - HPLTH_9_Y1");
        put("SL.RL1 - BRECL_7_Y1", "SL.RL1 - BRECL_7_Y1");
        put("SL.RL2 - BRECL_7_Y2", "SL.RL2 - BRECL_7_Y2");
        put("SL.RL3 - BRECL_7_Y3", "SL.RL3 - BRECL_7_Y3");
        put("SL.RL4 - BSPTE_8_Y4", "SL.RL4 - BSPTE_8_Y4");
        put("SL.RL5", "SL.RL5");
        put("SL.RL6", "SL.RL6");
        put("TC.BACA1 XXXX", "TC.BACA1 XXXX");
        put("TC.BACA3 - OCULP_7_Y3", "TC.BACA3 - OCULP_7_Y3");
        put("TC.BBBM1 - OBARM_7_Y1", "TC.BBBM1 - OBARM_7_Y1");
        put("TC.BBBM2 - OBARM_7_Y2", "TC.BBBM2 - OBARM_7_Y2");
        put("TC.BBBM3 - OBARM_7_Y3", "TC.BBBM3 - OBARM_7_Y3");
        put("TC.BBCA1 - OCULA_7_Y1", "TC.BBCA1 - OCULA_7_Y1");
        put("TC.BBCA2 - OCULA_7_Y2", "TC.BBCA2 - OCULA_7_Y2");
        put("TC.BBCA3 - OCULA_7_Y3", "TC.BBCA3 - OCULA_7_Y3");
        put("TC.CHEF1Accelerated", "TC.CHEF1Accelerated");
        put("TC.CHEF1DR", "TC.CHEF1DR");
        put("TC.CHEF2DR", "TC.CHEF2DR");
        put("TC.CHEF3DR", "TC.CHEF3DR");
        put("TC.CUL1 - OCULS_6_Y1", "TC.CUL1 - OCULS_6_Y1");
        put("TC.CUL2 - OCULS_6_Y2", "TC.CUL2 - OCULS_6_Y2");
        put("TC.EV PASTRY", "TC.EV PASTRY");
        put("TC.EVBARRTN", "TC.EVBARRTN");
        put("TC.EVFOODHYG", "TC.EVFOODHYG");
        put("TC.EVWINE", "TC.EVWINE");
        put("TC.HM1 - OHCMA_7_Y1", "TC.HM1 - OHCMA_7_Y1");
        put("TC.HM2 - OHCMA_7_Y2", "TC.HM2 - OHCMA_7_Y2");
        put("TC.HM3 - OHCMA_7_Y3", "TC.HM3 - OHCMA_7_Y3");
        put("TC.HM4 - OHCMA_8_Y4", "TC.HM4 - OHCMA_8_Y4");
        put("TC.HOSP1 - OHOST_6_Y1", "TC.HOSP1 - OHOST_6_Y1");
        put("TC.HOSP2 - OHOST_6_Y2", "TC.HOSP2 - OHOST_6_Y2");
        put("TC.TOU1 - FTOUR_7_Y1", "TC.TOU1 - FTOUR_7_Y1");
        put("TC.TOU2 - FTOUR_7_Y2", "TC.TOU2 - FTOUR_7_Y2");
        put("TC.TOU3 - FTOUR_7_Y3", "TC.TOU3 - FTOUR_7_Y3");
        put("TC.TOU4 - FTOUR_8_Y4", "TC.TOU4 - FTOUR_8_Y4");
        put("TC.TOU5-FTOUR_9_Y5", "TC.TOU5-FTOUR_9_Y5");
        put("TC.TRSM1 - FTRSM_8_Y1", "TC.TRSM1 - FTRSM_8_Y1");
        put("TC.TRSM2 - FTRSM_8_Y2", "TC.TRSM2 - FTRSM_8_Y2");
        put("TC.TRSM3 - FTRSM_8_Y3", "TC.TRSM3 - FTRSM_8_Y3");
        put("TC.TRSM4 - FTRSM_8_Y4", "TC.TRSM4 - FTRSM_8_Y4");
        put("UQ.DRAMA1 - GTHDR_8_Y1", "UQ.DRAMA1 - GTHDR_8_Y1");
        put("UQ.DRAMA2 - GTHDR_8_Y2", "UQ.DRAMA2 - GTHDR_8_Y2");
        put("UQ.DRAMA3 - GTHDR_8_Y3", "UQ.DRAMA3 - GTHDR_8_Y3");
        put("UQ.DRAMA4 - GTHDR_8_Y4", "UQ.DRAMA4 - GTHDR_8_Y4");
        put("UQ.MUS1 - GMUSC_8_Y1", "UQ.MUS1 - GMUSC_8_Y1");
        put("UQ.MUS2 - GMUSC_8_Y2", "UQ.MUS2 - GMUSC_8_Y2");
        put("UQ.MUS3 - GMUSC_8_Y3", "UQ.MUS3 - GMUSC_8_Y3");
        put("UQ.MUS4 - GMUSC_8_Y4", "UQ.MUS4 - GMUSC_8_Y4");
        put("UQ.MUS5R.1.GMUSC_9_Y1", "UQ.MUS5R.1.GMUSC_9_Y1");
        put("UQ.MUS5T.1.GMUSC_9_Y1", "UQ.MUS5T.1.GMUSC_9_Y1");
        put("UQ.MUS5T.2.GMUSC_9_Y2", "UQ.MUS5T.2.GMUSC_9_Y2");
        put("UQ.MUS6", "UQ.MUS6");
        put("UQ.MUSTCH5.1.GMUTE_9_Y1", "UQ.MUSTCH5.1.GMUTE_9_Y1");
        put("UQ.MUSTCH5.3.GMUTE_9_Y2", "UQ.MUSTCH5.3.GMUTE_9_Y2");
        put("UQ.POP1 - GPOPM_8_Y1", "UQ.POP1 - GPOPM_8_Y1");
        put("UQ.POP2 - GPOPM_8_Y2", "UQ.POP2 - GPOPM_8_Y2");
        put("UQ.POP3 - GPOPM_8_Y3", "UQ.POP3 - GPOPM_8_Y3");
        put("UQ.POP4 - GPOPM_8_Y4", "UQ.POP4 - GPOPM_8_Y4");
        put("UQ.PT.BASSOON", "UQ.PT.BASSOON");
        put("UQ.PT.BRASSENSM", "UQ.PT.BRASSENSM");
        put("UQ.PT.CELLO", "UQ.PT.CELLO");
        put("UQ.PT.CHAMBER", "UQ.PT.CHAMBER");
        put("UQ.PT.CHOIR", "UQ.PT.CHOIR");
        put("UQ.PT.CLARINET", "UQ.PT.CLARINET");
        put("UQ.PT.CLARINETENSM", "UQ.PT.CLARINETENSM");
        put("UQ.PT.COMPOSITION", "UQ.PT.COMPOSITION");
        put("UQ.PT.CONCBAND", "UQ.PT.CONCBAND");
        put("UQ.PT.DBLEBASS", "UQ.PT.DBLEBASS");
        put("UQ.PT.DRAMA", "UQ.PT.DRAMA");
        put("UQ.PT.FLUTE", "UQ.PT.FLUTE");
        put("UQ.PT.FLUTECLASS", "UQ.PT.FLUTECLASS");
        put("UQ.PT.FRENHORN", "UQ.PT.FRENHORN");
        put("UQ.PT.FRHORNENSM", "UQ.PT.FRHORNENSM");
        put("UQ.PT.GUITAR", "UQ.PT.GUITAR");
        put("UQ.PT.GUITARENSM.JNR", "UQ.PT.GUITARENSM.JNR");
        put("UQ.PT.GUITARENSM.SNR", "UQ.PT.GUITARENSM.SNR");
        put("UQ.PT.HARP", "UQ.PT.HARP");
        put("UQ.PT.HARPSICHORD", "UQ.PT.HARPSICHORD");
        put("UQ.PT.JAZZBIGBAND", "UQ.PT.JAZZBIGBAND");
        put("UQ.PT.JAZZJNRBAND", "UQ.PT.JAZZJNRBAND");
        put("UQ.PT.JAZZPIANO", "UQ.PT.JAZZPIANO");
        put("UQ.PT.JAZZVOCENSM", "UQ.PT.JAZZVOCENSM");
        put("UQ.PT.JUNIORBAND", "UQ.PT.JUNIORBAND");
        put("UQ.PT.JUNIORCERT", "UQ.PT.JUNIORCERT");
        put("UQ.PT.LEAVINGCERT", "UQ.PT.LEAVINGCERT");
        put("UQ.PT.MASCLASSACADEMIC", "UQ.PT.MASCLASSACADEMIC");
        put("UQ.PT.MASCLASSKEYB", "UQ.PT.MASCLASSKEYB");
        put("UQ.PT.MASCLASSSTRING", "UQ.PT.MASCLASSSTRING");
        put("UQ.PT.MASCLASSWIND", "UQ.PT.MASCLASSWIND");
        put("UQ.PT.MUSICIANSHIP", "UQ.PT.MUSICIANSHIP");
        put("UQ.PT.MUSTDSADULT", "UQ.PT.MUSTDSADULT");
        put("UQ.PT.OBOE", "UQ.PT.OBOE");
        put("UQ.PT.OPERASTUDIO", "UQ.PT.OPERASTUDIO");
        put("UQ.PT.ORGAN", "UQ.PT.ORGAN");
        put("UQ.PT.ORGANKBSKILLS", "UQ.PT.ORGANKBSKILLS");
        put("UQ.PT.PERCUSENSM", "UQ.PT.PERCUSENSM");
        put("UQ.PT.PERCUSSION", "UQ.PT.PERCUSSION");
        put("UQ.PT.PIANO", "UQ.PT.PIANO");
        put("UQ.PT.PIANO2NDINST", "UQ.PT.PIANO2NDINST");
        put("UQ.PT.PIANOENSM", "UQ.PT.PIANOENSM");
        put("UQ.PT.RECORDENSM", "UQ.PT.RECORDENSM");
        put("UQ.PT.RECORDER", "UQ.PT.RECORDER");
        put("UQ.PT.SAXOPHONE", "UQ.PT.SAXOPHONE");
        put("UQ.PT.SPEECHCLASS", "UQ.PT.SPEECHCLASS");
        put("UQ.PT.SPEECHINDV", "UQ.PT.SPEECHINDV");
        put("UQ.PT.SPEECHTHEORY", "UQ.PT.SPEECHTHEORY");
        put("UQ.PT.SYMPHONYORCH", "UQ.PT.SYMPHONYORCH");
        put("UQ.PT.SZCELLO", "UQ.PT.SZCELLO");
        put("UQ.PT.SZVIOLIN", "UQ.PT.SZVIOLIN");
        put("UQ.PT.THEORYIND", "UQ.PT.THEORYIND");
        put("UQ.PT.TRADGROUP", "UQ.PT.TRADGROUP");
        put("UQ.PT.TROMBONE", "UQ.PT.TROMBONE");
        put("UQ.PT.TRUMPET", "UQ.PT.TRUMPET");
        put("UQ.PT.TUBA", "UQ.PT.TUBA");
        put("UQ.PT.UILEANN", "UQ.PT.UILEANN");
        put("UQ.PT.VIOLA", "UQ.PT.VIOLA");
        put("UQ.PT.VIOLIN", "UQ.PT.VIOLIN");
        put("UQ.PT.VOCSUPPORTSTDS", "UQ.PT.VOCSUPPORTSTDS");
        put("UQ.PT.VOICE", "UQ.PT.VOICE");
        put("UQ.PT.WINDENSM", "UQ.PT.WINDENSM");
        put("UQ.PT.WINDWISE", "UQ.PT.WINDWISE");
        put("UQ.PT.WOODENSM", "UQ.PT.WOODENSM");
        put("UQ.PT.YTHMUSPROJ", "UQ.PT.YTHMUSPROJ");
        put("xTEMP", "xTEMP");
    }};

}
